spring:
  profiles:
    active: @profileActive@

---
server:
  port: 8098
  # 加上以下servlet内容，访问地址为 http://localhost:8098/spring-demo/swagger-ui.html，否则为 http://localhost:8098/swagger-ui.html，否则为
  servlet:
    context-path: /spring-best-practices

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  profiles: dev
  application:
    name: java-best-practices
  datasource:
    druid:
      platform: mysql
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#      url: jdbc:p6spy:mysql://localhost:3306/test
      url: jdbc:p6spy:mysql://192.168.3.21:3306/flyway_test
      username: root
      password: rmm19950822
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
        enabled: true
  #flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
  logging:
    level:
      org:
        flywaydb=debug

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    add-properties: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config::
  db-config:

#    逻辑删除/不删除值
    logic-delete-value: 1  # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 0  # 逻辑未删除值(默认为 0)

MYENGLISHNAME:
  value: angel

swagger:
  title: Best Practices-Dev
  contact:
    name: angel
    email: 18232466045@163.com
    url:
      version: 1.0.1
      description: SSM project best practices
      base-package: com.dmsdbj.team3.javaprojectbestpractices.controller
      base-path: /**
      license: "许可证"
      license-url: ""

---

server:
  port: 8082
  servlet:
    context-path: /spring-best-pratice
spring:
  profiles: test
  application:
    name: java-best-practices
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/best_practices_test
      username: root
      password: rmm19950822
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

swagger:
  title: Best Practices-Test
  contact:
    name: angel
    email: 18232466045@163.com
    url:
      version: 1.0.1
      description: SSM project best practices
      base-package: com.dmsdbj.team3.javaprojectbestpractices.controller
      base-path: /**
      license: "许可证"
      license-url: ""

---
spring:
  profiles: prod
  application:
    name: java-best-practices
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/best_practices_prod
      username: root
      password: 12345678
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

swagger:
  title: Best Practices-Test
  contact:
    name: angel
    email: 18232466045@163.com
    url:
      version: 1.0.1
      description: SSM project best practices
      base-package: com.dmsdbj.team3.javaprojectbestpractices.controller
      base-path: /**
      license: "许可证"
      license-url: ""
server:
  port: 8083
  servlet:
    context-path: /spring-best-pratice